name: Release Drafter

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter@021d4a46e5094a1d493a1a17cd26725f678d9e8e # v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
